version: "3.8"

services:
  db:
    networks:
      - myNet
    build: ./db-service
    environment:
      MYSQL_DATABASE: movies
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
      DATABASE_HOST: db
      MULTIPLESTATEMENTS: 'true'

  movies-service:
    networks:
      - myNet
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    build: ./movies-service
    ports:
      - "3257:3257"
    links:
      - "app:app"
    depends_on:
     - db
    restart: on-failure
  app:

    networks:
      - myNet
    command: node ./app/src/server.js
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
networks:
  myNet:
    driver: bridge