version: "3.8"

services:
  db:
    networks:
      - some-net
    build: ./db-service
    environment:
      MYSQL_DATABASE: movies
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
      DATABASE_HOST: db
  movies-service:
    networks:
      - some-net

    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    build: ./movies-service
    ports:
      - "3257:3257"
    depends_on:
     - db
    restart: on-failure
networks:
  some-net:
    driver: bridge